//
// Mani Admin Plugin
//
// Copyright (c) 2009 Giles Millward (Mani). All rights reserved.
//
// This file is part of ManiAdminPlugin.
//
// Mani Admin Plugin is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Mani Admin Plugin is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Mani Admin Plugin.  If not, see <http://www.gnu.org/licenses/>.
//

//



#ifndef MANI_LANGUAGE_H
#define MANI_LANGUAGE_H

extern	bool LoadLanguage(void);
extern  void FreeLanguage(void);
extern	char *Translate(int translate_id);

#define M_PRIMARY_MENU_ESCAPE (100)
#define M_PRIMARY_MENU_TITLE (101)
#define M_PRIMARY_MENU_PLAYER_MANAGEMENT (102)
#define M_PRIMARY_MENU_FUN_PLAYER_MANAGEMENT (103)
#define M_PRIMARY_MENU_MAP_MANAGEMENT (104)
#define M_PRIMARY_MENU_VOTE_MANAGEMENT (105)
#define M_PRIMARY_MENU_RESTRICT_WEAPONS (106)
#define M_PRIMARY_MENU_PLAY_SOUND (107)
#define M_PRIMARY_MENU_RCON_COMMANDS (108)
#define M_PRIMARY_MENU_PLUGIN_CONFIG (109)
#define M_PRIMARY_MENU_CHANGE_MAP (110)
#define M_PRIMARY_MENU_TURN_OFF_WAR_MODE (111)

#define M_MAP_MENU_ESCAPE (130)
#define M_MAP_MENU_TITLE (131)

#define M_NEXT_MAP_MENU_ESCAPE (140)
#define M_NEXT_MAP_MENU_TITLE (141)

#define M_KICK_MENU_ESCAPE (150)
#define M_KICK_MENU_TITLE (151)

#define M_SLAP_MENU_ESCAPE (160)
#define M_SLAP_MENU_TITLE (161)
#define M_SLAP_MENU_SLAP_AGAIN (162)
#define M_SLAP_REPEAT_MENU_ESCAPE (163)
#define M_SLAP_REPEAT_MENU_TITLE (164)

#define M_BLIND_MENU_ESCAPE (170)
#define M_BLIND_MENU_TITLE (171)

#define M_SWAP_MENU_ESCAPE (180)
#define M_SWAP_MENU_TITLE (181)

#define M_FREEZE_MENU_ESCAPE (190)
#define M_FREEZE_MENU_TITLE (191)
#define M_FREEZE_MENU_FROZEN (192)

#define M_DRUG_MENU_ESCAPE (200)
#define M_DRUG_MENU_TITLE (201)
#define M_DRUG_MENU_DRUGGED (202)

#define M_GIMP_MENU_ESCAPE (210)
#define M_GIMP_MENU_TITLE (211)
#define M_GIMP_MENU_GIMPED (212)

#define M_TELEPORT_MENU_ESCAPE (220)
#define M_TELEPORT_MENU_TITLE (221)
#define M_TELEPORT_MENU_SAVE_LOC_FIRST (222)

#define M_SLAY_MENU_ESCAPE (230)
#define M_SLAY_MENU_TITLE (231)

#define M_RCON_VOTE_MENU_ESCAPE (240)
#define M_RCON_VOTE_MENU_TITLE (241)

#define M_QUESTION_VOTE_MENU_ESCAPE (250)
#define M_QUESTION_VOTE_MENU_TITLE (251)

#define M_RCON_MENU_ESCAPE (260)
#define M_RCON_MENU_TITLE (261)

#define M_CLIENT_COMMAND_MENU_ESCAPE (270)
#define M_CLIENT_COMMAND_MENU_TITLE (271)

#define M_CLIENT_PLAYER_COMMAND_MENU_ESCAPE (280)
#define M_CLIENT_PLAYER_COMMAND_MENU_TITLE (281)

#define M_FUN_PLAYER_MANAGE_MENU_ESCAPE (290)
#define M_FUN_PLAYER_MANAGE_MENU_TITLE (291)
#define M_FUN_PLAYER_MANAGE_MENU_SLAP_PLAYER (292)
#define M_FUN_PLAYER_MANAGE_MENU_BLIND_PLAYER (293)
#define M_FUN_PLAYER_MANAGE_MENU_FREEZE_PLAYER (294)
#define M_FUN_PLAYER_MANAGE_MENU_DRUG_PLAYER (295)
#define M_FUN_PLAYER_MANAGE_MENU_GIMP_PLAYER (296)
#define M_FUN_PLAYER_MANAGE_MENU_TELEPORT_PLAYER (297)
#define M_FUN_PLAYER_MANAGE_MENU_SAVE_TELEPORT_LOC (298)
#define M_FUN_PLAYER_MANAGE_MENU_BURN_PLAYER (299)
#define M_FUN_PLAYER_MANAGE_MENU_NO_CLIP_PLAYER (300)
#define M_FUN_PLAYER_MANAGE_MENU_SET_SKIN (301)
#define M_FUN_PLAYER_MANAGE_MENU_TIME_BOMB_PLAYER (302)
#define M_FUN_PLAYER_MANAGE_MENU_FIRE_BOMB_PLAYER (303)
#define M_FUN_PLAYER_MANAGE_MENU_FREEZE_BOMB_PLAYER (304)
#define M_FUN_PLAYER_MANAGE_MENU_BEACON_PLAYER (305)

#define M_VOTE_TYPE_MENU_ESCAPE (310)
#define M_VOTE_TYPE_MENU_TITLE (311)
#define M_VOTE_TYPE_MENU_RCON_VOTE (312)
#define M_VOTE_TYPE_MENU_QUESTION_VOTE (313)
#define M_VOTE_TYPE_MENU_EXTEND_MAP_VOTE (314)
#define M_VOTE_TYPE_MENU_RANDOM_MAP_VOTE (315)
#define M_VOTE_TYPE_MENU_SINGLE_MAP_VOTE (316)
#define M_VOTE_TYPE_MENU_BUILD_MULTIMAP_VOTE (317)
#define M_VOTE_TYPE_MENU_START_MULTIMAP_VOTE (318)
#define M_VOTE_TYPE_MENU_CANCEL_VOTE (319)

#define M_MAP_CHANGE_TYPE_MENU_ESCAPE (330)
#define M_MAP_CHANGE_TYPE_MENU_TITLE (331)
#define M_MAP_CHANGE_TYPE_MENU_IMMEDIATE (332)
#define M_MAP_CHANGE_TYPE_MENU_END_OF_ROUND (333)
#define M_MAP_CHANGE_TYPE_MENU_END_OF_MAP (334)

#define M_BAN_OPTIONS_MENU_ESCAPE (350)
#define M_BAN_OPTIONS_MENU_TITLE (351)
#define M_BAN_OPTIONS_MENU_5_MINUTE (352)
#define M_BAN_OPTIONS_MENU_30_MINUTE (353)
#define M_BAN_OPTIONS_MENU_1_HOUR (354)
#define M_BAN_OPTIONS_MENU_2_HOUR (355)
#define M_BAN_OPTIONS_MENU_1_DAY (356)
#define M_BAN_OPTIONS_MENU_7_DAY (357)
#define M_BAN_OPTIONS_MENU_PERMANENT (358)

#define M_SLAP_OPTIONS_MENU_ESCAPE (370)
#define M_SLAP_OPTIONS_MENU_TITLE (371)
#define M_SLAP_OPTIONS_MENU_0_HEALTH (372)
#define M_SLAP_OPTIONS_MENU_1_HEALTH (373)
#define M_SLAP_OPTIONS_MENU_5_HEALTH (374)
#define M_SLAP_OPTIONS_MENU_10_HEALTH (375)
#define M_SLAP_OPTIONS_MENU_20_HEALTH (376)
#define M_SLAP_OPTIONS_MENU_50_HEALTH (377)
#define M_SLAP_OPTIONS_MENU_99_HEALTH (378)

#define M_BLIND_OPTIONS_MENU_ESCAPE (390)
#define M_BLIND_OPTIONS_MENU_TITLE (391)
#define M_BLIND_OPTIONS_MENU_UNBLIND (392)
#define M_BLIND_OPTIONS_MENU_PARTIAL (393)
#define M_BLIND_OPTIONS_MENU_FULL (394)

#define M_BAN_TYPE_MENU_ESCAPE (400)
#define M_BAN_TYPE_MENU_TITLE (401)
#define M_BAN_TYPE_MENU_STEAM (402)
#define M_BAN_TYPE_MENU_IP (403)
#define M_BAN_TYPE_MENU_AUTOBAN_NAME (404)

#define M_KICK_TYPE_MENU_ESCAPE (420)
#define M_KICK_TYPE_MENU_TITLE (421)
#define M_KICK_TYPE_MENU_KICK_NOW (422)
#define M_KICK_TYPE_MENU_NAME (423)
#define M_KICK_TYPE_MENU_STEAM (424)
#define M_KICK_TYPE_MENU_IP (425)

#define M_CLIENT_EXEC_OPTIONS_MENU_ESCAPE (440)
#define M_CLIENT_EXEC_OPTIONS_MENU_TITLE (441)
#define M_CLIENT_EXEC_OPTIONS_MENU_SINGLE (442)
#define M_CLIENT_EXEC_OPTIONS_MENU_ALL (443)
#define M_CLIENT_EXEC_OPTIONS_MENU_T (444)
#define M_CLIENT_EXEC_OPTIONS_MENU_CT (445)
#define M_CLIENT_EXEC_OPTIONS_MENU_SPEC (446)

#define M_PLUGIN_CONFIG_MENU_ESCAPE (460)
#define M_PLUGIN_CONFIG_MENU_TITLE (461)
#define M_PLUGIN_CONFIG_MENU_DISABLE_ADVERTS (462)
#define M_PLUGIN_CONFIG_MENU_ENABLE_ADVERTS (463)
#define M_PLUGIN_CONFIG_MENU_DISABLE_TK_PROTECT (464)
#define M_PLUGIN_CONFIG_MENU_ENABLE_TK_PROTECT (465)
#define M_PLUGIN_CONFIG_MENU_DISABLE_TK_FORGIVE (466)
#define M_PLUGIN_CONFIG_MENU_ENABLE_TK_FORGIVE (467)
#define M_PLUGIN_CONFIG_MENU_DISABLE_WAR_MODE (468)
#define M_PLUGIN_CONFIG_MENU_ENABLE_WAR_MODE (469)
#define M_PLUGIN_CONFIG_MENU_DISABLE_STATS (470)
#define M_PLUGIN_CONFIG_MENU_ENABLE_STATS (471)
#define M_PLUGIN_CONFIG_MENU_RESET_RANKS (472)

#define M_BAN_PLAYER_MENU_ESCAPE (500)
#define M_BAN_PLAYER_MENU_STEAM (501)
#define M_BAN_PLAYER_MENU_IP (502)

#define M_AUTOBAN_NAME_MENU_ESCAPE (510)
#define M_AUTOBAN_NAME_MENU_TITLE (511)

#define M_AUTOKICK_MENU_ESCAPE_STEAM (520)
#define M_AUTOKICK_MENU_ESCAPE_IP (521)
#define M_AUTOKICK_MENU_ESCAPE_NAME (522)
#define M_AUTOKICK_MENU_TITLE_STEAM (523)
#define M_AUTOKICK_MENU_TITLE_IP (524)
#define M_AUTOKICK_MENU_TITLE_NAME (525)

#define M_RESTRICT_MENU_ESCAPE (530)
#define M_RESTRICT_MENU_TITLE (531)
#define M_RESTRICT_MENU_UNRESTRICT (532)
#define M_RESTRICT_MENU_RESTRICT (533)

#define M_PLAY_SOUND_MENU_ESCAPE (540)
#define M_PLAY_SOUND_MENU_TITLE (541)

#define M_SYSTEM_VOTE_MENU_ESCAPE (550)
#define M_SYSTEM_VOTE_MENU_VOTE_NEXT_MAP_TITLE (551)
#define M_SYSTEM_VOTE_MENU_WILL_NEXT_MAP_TITLE (552)
#define M_SYSTEM_VOTE_MENU_EXTEND_MAP_TITLE (553)
#define M_SYSTEM_VOTE_MENU_THE_QUESTION_WAS (554)
#define M_SYSTEM_VOTE_MENU_THE_ANSWER_IS (555)

#define M_USER_VOTE_MAP_MENU_ESCAPE (560)
#define M_USER_VOTE_MAP_MENU_TITLE (561)

#define M_USER_VOTE_KICK_MENU_ESCAPE (570)
#define M_USER_VOTE_KICK_MENU_TITLE (571)

#define M_USER_VOTE_BAN_MENU_ESCAPE (580)
#define M_USER_VOTE_BAN_MENU_TITLE (581)

#define M_MAP_MANAGE_MENU_ESCAPE (590)
#define M_MAP_MANAGE_MENU_TITLE (591)
#define M_MAP_MANAGE_MENU_CHANGE_MAP (592)
#define M_MAP_MANAGE_MENU_SET_NEXT_MAP (593)

#define M_PLAYER_MANAGE_MENU_ESCAPE (610)
#define M_PLAYER_MANAGE_MENU_TITLE (611)
#define M_PLAYER_MANAGE_MENU_SLAY_PLAYER (612)
#define M_PLAYER_MANAGE_MENU_KICK_PLAYER (613)
#define M_PLAYER_MANAGE_MENU_BAN_PLAYER (614)
#define M_PLAYER_MANAGE_MENU_SWAP_PLAYER (615)
#define M_PLAYER_MANAGE_MENU_BALANCE_TEAMS (616)
#define M_PLAYER_MANAGE_MENU_CLIENT_COMMANDS (617)
#define M_PLAYER_MANAGE_MENU_MUTE_PLAYER (618)
#define M_PLAYER_MANAGE_MENU_SPEC_PLAYER (619)

#define M_FORGIVE_MENU_ESCAPE (630)
#define M_FORGIVE_MENU_TITLE (631)
#define M_FORGIVE_MENU_FORGIVE_PLAYER (632)
#define M_FORGIVE_MENU_SLAY_PLAYER (633)
#define M_FORGIVE_MENU_SLAP_PLAYER (634)
#define M_FORGIVE_MENU_BLIND_PLAYER (635)
#define M_FORGIVE_MENU_FREEZE_PLAYER (636)
#define M_FORGIVE_MENU_TAKE_CASH_FROM_PLAYER (637)
#define M_FORGIVE_MENU_DRUG_PLAYER (638)
#define M_FORGIVE_MENU_BURN_PLAYER (639)
#define M_FORGIVE_MENU_TIME_BOMB_PLAYER (640)
#define M_FORGIVE_MENU_FIRE_BOMB_PLAYER (641)
#define M_FORGIVE_MENU_FREEZE_BOMB_PLAYER (642)
#define M_FORGIVE_MENU_BEACON_PLAYER (643)

#define M_ACCEPT_VOTE_MENU_ESCAPE (660)
#define M_ACCEPT_VOTE_MENU_TITLE (661)

#define M_MENU_YES (670)
#define M_MENU_NO (671)
#define M_MENU_BACK (672)
#define M_MENU_MORE (673)
#define M_MENU_BACK_AMX (674)
#define M_MENU_MORE_AMX (675)
#define M_MENU_EXIT_AMX (676)

#define M_RANDOM_MAP_MENU_ESCAPE (700)
#define M_RANDOM_MAP_MENU_TITLE (701)

#define M_SINGLE_MAP_MENU_ESCAPE (710)
#define M_SINGLE_MAP_MENU_TITLE (711)

#define M_BUILD_MAP_MENU_ESCAPE (720)
#define M_BUILD_MAP_MENU_TITLE (721)
#define M_BUILD_MAP_MENU_DESELECT_MAP (722)
#define M_BUILD_MAP_MENU_SELECT_MAP (723)
#define M_BUILD_MAP_MENU_ADDED (724)

#define M_BURN_MENU_ESCAPE (740)
#define M_BURN_MENU_TITLE (741)

#define M_NO_CLIP_MENU_ESCAPE (750)
#define M_NO_CLIP_MENU_TITLE (751)
#define M_NO_CLIP_MENU_NO_CLIP (752)

#define M_MUTE_MENU_ESCAPE (760)
#define M_MUTE_MENU_TITLE (761)
#define M_MUTE_MENU_MUTED (762)

#define M_WEB_FAVOURITES_MENU_ESCAPE (770)
#define M_WEB_FAVOURITES_MENU_TITLE (771)

#define M_SETSKIN_MENU_ESCAPE (780)
#define M_SETSKIN_MENU_TITLE (781)

#define M_SKINOPTIONS_MENU_ESCAPE (782)
#define M_SKINOPTIONS_MENU_TITLE (783)

#define M_SPEC_MENU_ESCAPE (790)
#define M_SPEC_MENU_TITLE (791)

#define M_TIME_BOMB_MENU_ESCAPE (850)
#define M_TIME_BOMB_MENU_TITLE (851)

#define M_FIRE_BOMB_MENU_ESCAPE (852)
#define M_FIRE_BOMB_MENU_TITLE (853)

#define M_FREEZE_BOMB_MENU_ESCAPE (854)
#define M_FREEZE_BOMB_MENU_TITLE (855)

#define M_BEACON_MENU_ESCAPE (856)
#define M_BEACON_MENU_TITLE (857)

#define M_QUAKE_PREPARE_TO_FIGHT (800)
#define M_QUAKE_FIRST_BLOOD (801)
#define M_QUAKE_HUMILIATION (802)
#define M_QUAKE_MULTI_KILL (803)
#define M_QUAKE_DOMINATING (804)
#define M_QUAKE_RAMPAGE (805)
#define M_QUAKE_KILLING_SPREE (806)
#define M_QUAKE_MONSTER_KILL (807)
#define M_QUAKE_UNSTOPPABLE (808)
#define M_QUAKE_ULTRA_KILL (809)
#define M_QUAKE_GOD_LIKE (810)
#define M_QUAKE_WICKED_SICK (811)
#define M_QUAKE_LUDICROUS_KILL (812)
#define M_QUAKE_HOLY_SHIT (813)
#define M_QUAKE_HEADSHOT (814)



#endif